### ISSUE TITLE
作者您好,请教安装问题

### ISSUE THREAD

**Issue by wxliuxh** [gyteng/shadowsocks-manager#2]
作者您好,我以前一直用的lnmp.无意间发现您的作品.想研究一下.可是按照安装过程走一下出现一些问题.谷歌的也不全.特来请教一下.....系统是centos-6-x86_64-minimal

1、环境准备：

mkdir /home/mongodb
mkdir /data/mongodata -p
mkdir /data/log/mongolog -p
2、下载：

1 curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.6.tgz
3、安装：

tar xf mongodb-linux-x86_64-3.2.6.tgz
cd mongodb-linux-x86_64-3.2.6
cp -r * /home/mongodb
为了便于命令启动，需要编辑全局变量PATH

1 vim /etc/profile.d/mongo.sh
2 export PATH=$PATH:/home/mongodb/bin
source /etc/profile.d/mongo.sh
4、启动服务
首先查看mongod的帮助信息
 mongod --help
    
  ////////
 yum install gcc-c++ make
 yum install -y nodejs

yum install git
git clone git@github.com:gyteng/shadowsocks-manager.git(wget下载的时候提示密钥错误无法下载..手动下载再传到服务器的)
cd shadowsocks-manager
npm install -g bower
npm install
bower install
--bower install这一步提示需要执行 bower install --allow-root
然后出现好多版本选择..不知道选哪个...
//////
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#~1.2.5 which resolved to 1.2.29 and is required by angular-qr#0.2.0
    2) angular#1.5.6 which resolved to 1.5.6 and is required by angular-animate#1.5.6, angular-aria#1.5.6, angular-messages#1.5.6
    3) angular#^1.0.8 which resolved to 1.5.6 and is required by angular-ui-router#0.2.18
    4) angular#1.x which resolved to 1.5.6 and is required by angular-chart.js#0.10.2
    5) angular#^1.4.8 which resolved to 1.5.6 and is required by angular-material#1.0.9

Prefix the choice with ! to persist it to bower.json

? Answer 
////////
然后选了个3.最后修改JS里的网址后.执行.访问对应的网站一片空白...抓狂

**Comment by gyteng** [comment]
bower安装的时候通常选高版本即可，比如angular选1.5.6版的。

目前还在开发新功能，所以问题会比较多，文档我也没时间写完整。

**Comment by wxliuxh** [comment]
呃...重新装了一次莫名其妙打开了...然后注册账号.后台提示 激活码发送失败  点重新发送也没反应了.
[2016-06-04 15:54:58.128] [WARN] auth - [liuxh3388@gmail.com][********]邮箱未验证用户尝试登录
激活码发送失败
no history
[2016-06-04 15:56:01.482] [WARN] auth - [0ee170be07497e9c141752f4cf95392e][liuxh3388@gmail.com]激活码发送失败
点重新发送也没反应了.
//////////配置如下
exports.conf = {
    db: {
        host: '127.0.0.1',
        port: '27017',
        name: 'Shadowsocks-Manager'
    },
    admin: {
        email: 'liuxh3388@gmail.com',
        password: '随便的密码'
    },
    mail: {
        address: 'liuxh3388@gmail.com',
        password: '谷歌的密码',
        smtp: 'smtp.gmail.com',
        webaddress: 'http://23.107.138.173:6003'
    },
    express: {
        port: 6003
    }
};
/////////

**Comment by gyteng** [comment]
使用gmail作为发送激活码的邮箱，需要先到[这个地址](https://www.google.com/settings/security/lesssecureapps)关闭一个安全设置。参见[这里](https://nodemailer.com/using-gmail/)的解释。

**Comment by wxliuxh** [comment]
感谢您的热心解答..我注册了账号进去发现不是管理员.这个如何设置呢..    我在js里修改了并且用这个邮箱注册的.可是不行
//
admin: {
        email: 'liuxh3388@gmail.com',
        password: '909834834'
    },
//

**Comment by gyteng** [comment]
管理员帐号是首次启动的时候自动生成的，
就是config.js的这段定义的：

```
admin: {
        email: 'liuxh3388@gmail.com',
        password: '随便的密码'
},
```

如果不行，可以清空数据库再运行。

**Comment by wxliuxh** [comment]
SS后端已安装~
ssserver --manager-address 0.0.0.0:6001 -c /root/config.json
///config.json
{
    "server":"0.0.0.0",
    "server_port":8989,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"1112",
    "timeout":600,
    "method":"aes-256-cfb"
}
///

服务器添加IP,管理端口6001和加密方式

管理员登陆后分配服务器给账号.能选择服务器.端口选择哪里是一片空白,,,,呃,,这个怎么整

**Comment by gyteng** [comment]
需要先在“服务器管理”的菜单里，点详情，再点右下角的+号添加端口和密码，可以添加若干个。添加后还要设置这个端口的流量和时长，过期会自动关闭。
>
>
只有在这里界面添加了端口后，才能分配给普通用户使用。

**Comment by wxliuxh** [comment]
感谢.成功架设起来了.稍后整理下过程发上来,
目前测试很棒!就是mongodb数据库感觉不安全啊....只要知道网站和端口就直接能操作....

**Comment by wxliuxh** [comment]
对了.续费码使用后.并不会自动删除.在管理界面没有已使用和未使用标示.有些不方便

**Comment by gyteng** [comment]
续费码的问题会在最近修复，目前只是保证一个基础功能可用，界面还不太好用。

**Comment by denvey** [comment]
端口可以自动分配给注册用户吗

**Comment by gyteng** [comment]
本身有这个功能的

2016-07-14 23:10 GMT+08:00 denvey <notifications@github.com>:

**Comment by denvey** [comment]
哦，好的，我再看看，谢谢

**Comment by wangruifei** [comment]
还有问题吗


2016-08-03 14:59 GMT+08:00 denvey <notifications@github.com>:

**Comment by slarkcoder** [comment]
@wxliuxh 你的部署过程能写篇文章发出来吗？谢谢！

**Comment by wwgc** [comment]
@wxliuxh mongodb是可以设置账号和密码的。
