### ISSUE TITLE
请问这个后端打算提供api吗？

### ISSUE THREAD

**Issue by pexcn** [gyteng/shadowsocks-manager#3]
如果可以的话，我想写个material design风格的android客户端…

**Comment by pexcn** [comment]
很惭愧…想做一点微小的工作，但是，才学android没多久…想找个感兴趣的项目练练手…

**Comment by gyteng** [comment]
你觉得应该提供怎样的API？
2016年6月5日 02:59，"Max pexcn" <notifications@github.com>写道：

**Comment by pexcn** [comment]
最好是json格式的

**Comment by gyteng** [comment]
目前用的所有Restful接口都是JSON格式的，只是我没有具体写文档，你可以自己查代码。

但我不明白为什么需要写一个Android客户端。

**Comment by pexcn** [comment]
好的…我对翻墙工具之类的比较感兴趣…所以想折腾下练练手

**Comment by pexcn** [comment]
nodejs没学过，尽量学习下吧😅😅

**Comment by gyteng** [comment]
接口地址可以看/server/routes下的文件，你先搞定登录验证的话，其他都好办。

**Comment by pexcn** [comment]
好的…尽量尝试…
