### ISSUE TITLE
投稿2 教程 后端

### ISSUE THREAD

**Issue by wxliuxh** [gyteng/shadowsocks-manager#6]
shadowsocks-python并启用chacha20加密

yum -y update
yum install -y gcc
yum install m2crypto
yum install python-setuptools && easy_install pip
pip install shadowsocks

cd /root
wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz
tar zxvf libsodium-1.0.10.tar.gz
cd libsodium*
./configure
make && make install

# 修复关联
echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
ldconfig

--------------------------------
ssserver --manager-address 0.0.0.0:6001 -c /root/config.json
/////config.json
{
    "server":"0.0.0.0",
    "server_port":8989,
    "local_port":1080,
    "password":"jhrjhjkjker",
    "timeout":60,
    "method":"chacha20"
}

/////

客户端切记不要开启 {一次性认证}
服务端支持UDP

**Comment by pexcn** [comment]
libev版多好
