### ISSUE TITLE
加密的疑问

### ISSUE THREAD

**Issue by wxliuxh** [gyteng/shadowsocks-manager#7]
在网站里设置加密为256.
ssserver --manager-address 0.0.0.0:6001 -c /root/config.json
命令开启的json里设置为chacha20...然后启动后发现是以json里的加密为准的...网站设置的无效...这是我哪里设置错了吗

**Comment by gyteng** [comment]
加密方式并不能通过网站修改，只是设置的时候要设成跟实际情况相同的，会影响二维码的生成。
2016年6月5日 上午9:03，"wxliuxh" <notifications@github.com>写道：
